### ISSUE TITLE
'docker rm -v' versus 'docker rm'

### ISSUE THREAD

**Issue by rrusk** [PhyDaC/scoop-env#2]
The Makefile "docker rm" leaves volumes associated with containers.  These include visualizer-db:/data/db, endpoint-db:/data/db and hub-db:/data/db which can be many GB in size.  The reason for this behaviour is that it allows the database content to persist when the container is destroyed.  However, this may not be desirable.  If so, use "docker rm -v" rather than "docker rm".  Otherwise, unreferenced volumes will be left in /var/lib/docker/vfs and /var/lib/docker/volumes and will eventually consume all of the available disk space.  At this point in time, docker doesn't have a volume manager.  Work in progress addressing this is at http://github.com/cpuguy83/docker-volumes.  A good discussion on how this issue comes up is at http://container42.com/2014/11/03/docker-indepth-volumes/

Places where this substitution should be considered are:

./Makefile:	docker rm endpoint-db || true
./Makefile:	docker rm endpoint || true
./Makefile:	docker rm hub-db || true
./Makefile:	docker rm hub || true
./Makefile:	docker rm visualizer-db || true
./Makefile:	docker rm visualizer || true
./Makefile:	docker rm hubapi || true

**Comment by DerekRoberts** [comment]
The change has been made here as well as the upcoming pdc-env.  Great suggestion, thanks!
